### ISSUE TITLE
Issue with field "subcategory_credit_amount_preceding"

### ISSUE THREAD

**Issue by daniellueddecke** [rienafairefr/nYNABapi#17]
Hi there,

I was trying your csimport.py and ofximport.py scripts. Both come up with the following error:
`ERROR:pynYNAB:Encountered field subcategory_credit_amount_preceding in a dictionary to create an entity of type <class 'pynYNAB.budget.Transaction'>`

It doesn't matter which csv files, schemas, or ofx files I am using...

Am I doing something wrong?

Thanks for your work and best regards,
Daniel

**Comment by rienafairefr** [comment]
Hi Daniel,
You did nothing wrong ^^ This is a typical error message to inform us here that the nYnab API changed a bit. It's an unfortunate consequence of using an undocumented internal API as a public API. I can have no guarantee that what I reverse engineered won't change at any time. I'll look into it, there is probably a lot of changes that happened since last time I committed. 
Sorry for the inconvenience !

**Comment by daniellueddecke** [comment]
Okay, cool.
Thank you!
