### ISSUE TITLE
The server knows more about this device than we know about ourselves

### ISSUE THREAD

**Issue by tovolkmar** [rienafairefr/nYNABapi#23]
Hi,

finally i got everything up and running. All created transactions a published in the other clients. That looks good.
After creating and adding the transaction to the client i get the following log error: **The server knows more about this device than we know about ourselves**
Is there something i missed, or is this just an information?

Thanks again for your help.

Best regards,
Tobias

**Comment by rienafairefr** [comment]
Hi Tobias,
This is a recurrent problem that is due to the way we talk with the API. I've reverse engineered the protocol partly but the way the server knows what to sync, by how much the client lags behind the server data, etc, this is still not 100% working. This is not a critical error and should not stop the sync from completing. I've seen it completely fail the sync for multiple sync in series, but for a single sync from nothing it should work. 
Sorry about the inconvenience :-)
Cheers
